### ISSUE TITLE
Update "yarn link" section CONTRIBUTING.md with "Yalc"

### ISSUE THREAD

**Issue by robinpiets** [Amsterdam/amsterdam-styled-components#1084] opened 2020-08-25 09:26 UTC
@jonkoops Can you update the `https://github.com/Amsterdam/amsterdam-styled-components/blob/master/docs/CONTRIBUTING.md` file with Yalc explaination?

**Comment by jonkoops** [comment] 2020-08-31 08:22
Duplicate of #882

**Closed by jonkoops** 2020-08-31 08:22 UTC
